### PR TITLE
Add terraform operation parameter

### PR DESCRIPTION
**Pull request by noor-shimul**
- Add terraform operation parameter to allow us to run pipeline manually in `plan` mode
- Update deprecated parameter and create variables in module to pass custom values

### CODE REVIEW

**Comment by staff-infrastructure-moj** [comment]
Environment: dev. Security Scan of Stage: dev has failed a IaC security scan, Please look at https://dev.azure.com/MoJ-OFFICIAL/Velocity-Landing-Zone/_build/results?buildId=66327&view=ms.vss-test-web.build-test-results-tab

**Comment by staff-infrastructure-moj** [comment]
Environment: prod. Pipeline Stage: prod
```
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # azurerm_private_dns_txt_record.offlineprint will be updated in-place
  ~ resource "azurerm_private_dns_txt_record" "offlineprint" {
        id                  = "/subscriptions/876eef88-ec3d-47db-b101-ec6f9daefb65/resourceGroups/rg-xwc-dnsresolve-001/providers/Microsoft.Network/privateDnsZones/print.internal.xcp/TXT/offlinemode"
        name                = "offlinemode"
        tags                = {}
        # (4 unchanged attributes hidden)

      - record {
          - value = "XWC.OfflineMode.Enabled=FALSE" -> null
        }
      + record {
          + value = "FALSE"
        }
    }

  # module.device-manager.azurerm_mssql_elasticpool.elastic_pool will be updated in-place
  ~ resource "azurerm_mssql_elasticpool" "elastic_pool" {
        id                             = "/subscriptions/876eef88-ec3d-47db-b101-ec6f9daefb65/resourceGroups/rg-xwc-app-001/providers/Microsoft.Sql/servers/sqlxwcdmsrv003/elasticPools/xwc-prod-pool"
        name                           = "xwc-prod-pool"
        tags                           = {
            "ApplicationName"  = "VelocityLandingZone"
            "BusinessUnit"     = "MOJ"
            "CostCentre"       = "MOJ"
            "OwnerName"        = "rob.ashworth@justice.gov.uk"
            "ProjectStartDate" = "05102020"
            "RequesterName"    = "rob.ashworth@justice.gov.uk"
            "ServiceLevel"     = "Gold"
        }
        # (8 unchanged attributes hidden)

      ~ per_database_settings {
          ~ max_capacity = 50 -> 20
          ~ min_capacity = 20 -> 10
        }

      ~ sku {
          ~ capacity = 200 -> 100
            name     = "StandardPool"
            # (1 unchanged attribute hidden)
        }
    }

  # module.device-manager.azurerm_mssql_server.sql_server will be updated in-place
  ~ resource "azurerm_mssql_server" "sql_server" {
      ~ connection_policy                    = "Redirect" -> "Default"
        id                                   = "/subscriptions/876eef88-ec3d-47db-b101-ec6f9daefb65/resourceGroups/rg-xwc-app-001/providers/Microsoft.Sql/servers/sqlxwcdmsrv003"
        name                                 = "sqlxwcdmsrv003"
        tags                                 = {
            "ApplicationName"  = "VelocityLandingZone"
            "BusinessUnit"     = "MOJ"
            "CostCentre"       = "MOJ"
            "OwnerName"        = "rob.ashworth@justice.gov.uk"
            "ProjectStartDate" = "05102020"
            "RequesterName"    = "rob.ashworth@justice.gov.uk"
            "ServiceLevel"     = "Gold"
        }
        # (10 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 3 to change, 0 to destroy.

**Comment by staff-infrastructure-moj** [comment]
Environment: prod. Security Scan of Stage: prod has failed a IaC security scan, Please look at https://dev.azure.com/MoJ-OFFICIAL/Velocity-Landing-Zone/_build/results?buildId=66327&view=ms.vss-test-web.build-test-results-tab

**Comment by staff-infrastructure-moj** [comment]
Environment: dev. Pipeline Stage: dev
```
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.device-manager.azurerm_mssql_elasticpool.elastic_pool will be updated in-place
  ~ resource "azurerm_mssql_elasticpool" "elastic_pool" {
        id                             = "/subscriptions/779c236c-a27b-405d-b0b8-0bbb5f7b5c67/resourceGroups/rg-xwc-app-001/providers/Microsoft.Sql/servers/sqlxwcdmsrv001/elasticPools/xwc-dev-pool"
        name                           = "xwc-dev-pool"
        tags                           = {
            "ApplicationName"  = "VelocityLandingZone"
            "BusinessUnit"     = "MOJ"
            "CostCentre"       = "MOJ"
            "OwnerName"        = "rob.ashworth@justice.gov.uk"
            "ProjectStartDate" = "05102020"
            "RequesterName"    = "rob.ashworth@justice.gov.uk"
            "ServiceLevel"     = "Gold"
        }
        # (8 unchanged attributes hidden)

      ~ per_database_settings {
          ~ max_capacity = 20 -> 50
          ~ min_capacity = 10 -> 20
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

**Comment by staff-infrastructure-moj** [comment]
Environment: dev. Security Scan of Stage: dev has failed a IaC security scan, Please look at https://dev.azure.com/MoJ-OFFICIAL/Velocity-Landing-Zone/_build/results?buildId=66334&view=ms.vss-test-web.build-test-results-tab

**Comment by staff-infrastructure-moj** [comment]
Environment: prod. Pipeline Stage: prod
```
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.device-manager.azurerm_mssql_server.sql_server will be updated in-place
  ~ resource "azurerm_mssql_server" "sql_server" {
      ~ connection_policy                    = "Redirect" -> "Default"
        id                                   = "/subscriptions/876eef88-ec3d-47db-b101-ec6f9daefb65/resourceGroups/rg-xwc-app-001/providers/Microsoft.Sql/servers/sqlxwcdmsrv003"
        name                                 = "sqlxwcdmsrv003"
        tags                                 = {
            "ApplicationName"  = "VelocityLandingZone"
            "BusinessUnit"     = "MOJ"
            "CostCentre"       = "MOJ"
            "OwnerName"        = "rob.ashworth@justice.gov.uk"
            "ProjectStartDate" = "05102020"
            "RequesterName"    = "rob.ashworth@justice.gov.uk"
            "ServiceLevel"     = "Gold"
        }
        # (10 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

**Comment by staff-infrastructure-moj** [comment]
Environment: prod. Security Scan of Stage: prod has failed a IaC security scan, Please look at https://dev.azure.com/MoJ-OFFICIAL/Velocity-Landing-Zone/_build/results?buildId=66334&view=ms.vss-test-web.build-test-results-tab

**Comment by staff-infrastructure-moj** [comment]
Environment: dev. Security Scan of Stage: dev has failed a IaC security scan, Please look at https://dev.azure.com/MoJ-OFFICIAL/Velocity-Landing-Zone/_build/results?buildId=66359&view=ms.vss-test-web.build-test-results-tab

**Comment by staff-infrastructure-moj** [comment]
Environment: dev. Security Scan of Stage: dev has failed a IaC security scan, Please look at https://dev.azure.com/MoJ-OFFICIAL/Velocity-Landing-Zone/_build/results?buildId=66361&view=ms.vss-test-web.build-test-results-tab

**Comment by staff-infrastructure-moj** [comment]
Environment: prod. Security Scan of Stage: prod has failed a IaC security scan, Please look at https://dev.azure.com/MoJ-OFFICIAL/Velocity-Landing-Zone/_build/results?buildId=66361&view=ms.vss-test-web.build-test-results-tab

**Comment by staff-infrastructure-moj** [comment]
Environment: dev. Security Scan of Stage: dev has failed a IaC security scan, Please look at https://dev.azure.com/MoJ-OFFICIAL/Velocity-Landing-Zone/_build/results?buildId=66366&view=ms.vss-test-web.build-test-results-tab

**Comment by staff-infrastructure-moj** [comment]
Environment: prod. Security Scan of Stage: prod has failed a IaC security scan, Please look at https://dev.azure.com/MoJ-OFFICIAL/Velocity-Landing-Zone/_build/results?buildId=66366&view=ms.vss-test-web.build-test-results-tab

**Review by kokulans — APPROVED** [review]
Looks good

**Pull request merged**
