### PR TITLE
Bump azurem 3.101.0 to 3.114.0 and random 3.6.1 to 3.6.2

### PR DESCRIPTION
**Pull request by alancollier142**
Bumps [hashicorp/azurerm](https://github.com/hashicorp/terraform-provider-azurerm) from 3.101.0 to 3.114.0.

Bumps [hashicorp/random](https://github.com/hashicorp/terraform-provider-random) from 3.61.0 to 3.62.0.

### CODE REVIEW

**Comment by staff-infrastructure-moj** [comment]
Environment: dev. Security Scan of Stage: dev has failed a IaC security scan, Please look at https://dev.azure.com/MoJ-OFFICIAL/Velocity-Landing-Zone/_build/results?buildId=53339&view=ms.vss-test-web.build-test-results-tab

**Comment by staff-infrastructure-moj** [comment]
Environment: prod. Pipeline Stage: prod
```
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.cloud-agent.azurerm_virtual_machine.VM["vmxwcca01"] will be updated in-place
  ~ resource "azurerm_virtual_machine" "VM" {
        id                               = "/subscriptions/876eef88-ec3d-47db-b101-ec6f9daefb65/resourceGroups/rg-xwc-app-001/providers/Microsoft.Compute/virtualMachines/vmxwcca01"
        name                             = "vmxwcca01"
        tags                             = {
            "ApplicationName"  = "VelocityLandingZone"
            "BusinessUnit"     = "MOJ"
            "CostCentre"       = "MOJ"
            "OwnerName"        = "rob.ashworth@justice.gov.uk"
            "ProjectStartDate" = "05102020"
            "RequesterName"    = "rob.ashworth@justice.gov.uk"
            "ServiceLevel"     = "Gold"
            "UpdateClass"      = "Gold1"
        }
        # (8 unchanged attributes hidden)

      - identity {
          - identity_ids = [] -> null
          - principal_id = "cb0e5d5b-f5da-4044-8864-a78f2414c065" -> null
          - tenant_id    = "c6874728-71e6-41fe-a9e1-2e8c36776ad8" -> null
          - type         = "SystemAssigned" -> null
        }

        # (6 unchanged blocks hidden)
    }

  # module.cloud-agent.azurerm_virtual_machine.VM["vmxwcca02"] will be updated in-place
  ~ resource "azurerm_virtual_machine" "VM" {
        id                               = "/subscriptions/876eef88-ec3d-47db-b101-ec6f9daefb65/resourceGroups/rg-xwc-app-001/providers/Microsoft.Compute/virtualMachines/vmxwcca02"
        name                             = "vmxwcca02"
        tags                             = {
            "ApplicationName"  = "VelocityLandingZone"
            "BusinessUnit"     = "MOJ"
            "CostCentre"       = "MOJ"
            "OwnerName"        = "rob.ashworth@justice.gov.uk"
            "ProjectStartDate" = "05102020"
            "RequesterName"    = "rob.ashworth@justice.gov.uk"
            "ServiceLevel"     = "Gold"
            "UpdateClass"      = "Gold2"
        }
        # (8 unchanged attributes hidden)

      - identity {
          - identity_ids = [] -> null
          - principal_id = "e7d90233-67d8-4fe5-ab88-60ff8ea7639e" -> null
          - tenant_id    = "c6874728-71e6-41fe-a9e1-2e8c36776ad8" -> null
          - type         = "SystemAssigned" -> null
        }

        # (6 unchanged blocks hidden)
    }

  # module.cloud-agent.azurerm_virtual_machine.VM["vmxwcca03"] will be updated in-place
  ~ resource "azurerm_virtual_machine" "VM" {
        id                               = "/subscriptions/876eef88-ec3d-47db-b101-ec6f9daefb65/resourceGroups/rg-xwc-app-001/providers/Microsoft.Compute/virtualMachines/vmxwcca03"
        name                             = "vmxwcca03"
        tags                             = {
            "ApplicationName"  = "VelocityLandingZone"
            "BusinessUnit"     = "MOJ"
            "CostCentre"       = "MOJ"
            "OwnerName"        = "rob.ashworth@justice.gov.uk"
            "ProjectStartDate" = "05102020"
            "RequesterName"    = "rob.ashworth@justice.gov.uk"
            "ServiceLevel"     = "Gold"
            "UpdateClass"      = "Gold1"
        }
        # (8 unchanged attributes hidden)

      - identity {
          - identity_ids = [] -> null
          - principal_id = "270dfd83-0966-44e2-8d79-bb276baee9cb" -> null
          - tenant_id    = "c6874728-71e6-41fe-a9e1-2e8c36776ad8" -> null
          - type         = "SystemAssigned" -> null
        }

        # (6 unchanged blocks hidden)
    }

  # module.cloud-agent.azurerm_virtual_machine.VM["vmxwcca04"] will be updated in-place
  ~ resource "azurerm_virtual_machine" "VM" {
        id                               = "/subscriptions/876eef88-ec3d-47db-b101-ec6f9daefb65/resourceGroups/rg-xwc-app-001/providers/Microsoft.Compute/virtualMachines/vmxwcca04"
        name                             = "vmxwcca04"
        tags                             = {
            "ApplicationName"  = "VelocityLandingZone"
            "BusinessUnit"     = "MOJ"
            "CostCentre"       = "MOJ"
            "OwnerName"        = "rob.ashworth@justice.gov.uk"
            "ProjectStartDate" = "05102020"
            "RequesterName"    = "rob.ashworth@justice.gov.uk"
            "ServiceLevel"     = "Gold"
            "UpdateClass"      = "Gold2"
        }
        # (8 unchanged attributes hidden)

      - identity {
          - identity_ids = [] -> null
          - principal_id = "5bf46218-cc1a-46ff-a5ce-388c7e06fbcb" -> null
          - tenant_id    = "c6874728-71e6-41fe-a9e1-2e8c36776ad8" -> null
          - type         = "SystemAssigned" -> null
        }

        # (6 unchanged blocks hidden)
    }

  # module.cloud-agent.azurerm_virtual_machine.VM["vmxwcca05"] will be updated in-place
  ~ resource "azurerm_virtual_machine" "VM" {
        id                               = "/subscriptions/876eef88-ec3d-47db-b101-ec6f9daefb65/resourceGroups/rg-xwc-app-001/providers/Microsoft.Compute/virtualMachines/vmxwcca05"
        name                             = "vmxwcca05"
        tags                             = {
            "ApplicationName"  = "VelocityLandingZone"
            "BusinessUnit"     = "MOJ"
            "CostCentre"       = "MOJ"
            "OwnerName"        = "rob.ashworth@justice.gov.uk"
            "ProjectStartDate" = "05102020"
            "RequesterName"    = "rob.ashworth@justice.gov.uk"
            "ServiceLevel"     = "Gold"
            "UpdateClass"      = "Gold1"
        }
        # (8 unchanged attributes hidden)

      - identity {
          - identity_ids = [] -> null
          - principal_id = "b8c0bf52-7803-4bab-88eb-14f273085036" -> null
          - tenant_id    = "c6874728-71e6-41fe-a9e1-2e8c36776ad8" -> null
          - type         = "SystemAssigned" -> null
        }

        # (6 unchanged blocks hidden)
    }

  # module.cloud-agent.azurerm_virtual_machine.VM["vmxwcca06"] will be updated in-place
  ~ resource "azurerm_virtual_machine" "VM" {
        id                               = "/subscriptions/876eef88-ec3d-47db-b101-ec6f9daefb65/resourceGroups/rg-xwc-app-001/providers/Microsoft.Compute/virtualMachines/vmxwcca06"
        name                             = "vmxwcca06"
        tags                             = {
            "ApplicationName"  = "VelocityLandingZone"
            "BusinessUnit"     = "MOJ"
            "CostCentre"       = "MOJ"
            "OwnerName"        = "rob.ashworth@justice.gov.uk"
            "ProjectStartDate" = "05102020"
            "RequesterName"    = "rob.ashworth@justice.gov.uk"
            "ServiceLevel"     = "Gold"
            "UpdateClass"      = "Gold2"
        }
        # (8 unchanged attributes hidden)

      - identity {
          - identity_ids = [] -> null
          - principal_id = "afd288a5-7891-46ae-980a-31d402dae436" -> null
          - tenant_id    = "c6874728-71e6-41fe-a9e1-2e8c36776ad8" -> null
          - type         = "SystemAssigned" -> null
        }

        # (6 unchanged blocks hidden)
    }

  # module.cloud-agent.azurerm_virtual_machine.VM["vmxwcca07"] will be updated in-place
  ~ resource "azurerm_virtual_machine" "VM" {
        id                               = "/subscriptions/876eef88-ec3d-47db-b101-ec6f9daefb65/resourceGroups/rg-xwc-app-001/providers/Microsoft.Compute/virtualMachines/vmxwcca07"
        name                             = "vmxwcca07"
        tags                             = {
            "ApplicationName"  = "VelocityLandingZone"
            "BusinessUnit"     = "MOJ"
            "CostCentre"       = "MOJ"
            "OwnerName"        = "rob.ashworth@justice.gov.uk"
            "ProjectStartDate" = "05102020"
            "RequesterName"    = "rob.ashworth@justice.gov.uk"
            "ServiceLevel"     = "Gold"
            "UpdateClass"      = "Gold1"
        }
        # (8 unchanged attributes hidden)

      - identity {
          - identity_ids = [] -> null
          - principal_id = "0d2aae9e-e3a6-40be-a2d3-d5b6a5c923e0" -> null
          - tenant_id    = "c6874728-71e6-41fe-a9e1-2e8c36776ad8" -> null
          - type         = "SystemAssigned" -> null
        }

        # (6 unchanged blocks hidden)
    }

  # module.cloud-agent.azurerm_virtual_machine.VM["vmxwcca08"] will be updated in-place
  ~ resource "azurerm_virtual_machine" "VM" {
        id                               = "/subscriptions/876eef88-ec3d-47db-b101-ec6f9daefb65/resourceGroups/rg-xwc-app-001/providers/Microsoft.Compute/virtualMachines/vmxwcca08"
        name                             = "vmxwcca08"
        tags                             = {
            "ApplicationName"  = "VelocityLandingZone"
            "BusinessUnit"     = "MOJ"
            "CostCentre"       = "MOJ"
            "OwnerName"        = "rob.ashworth@justice.gov.uk"
            "ProjectStartDate" = "05102020"
            "RequesterName"    = "rob.ashworth@justice.gov.uk"
            "ServiceLevel"     = "Gold"
            "UpdateClass"      = "Gold2"
        }
        # (8 unchanged attributes hidden)

      - identity {
          - identity_ids = [] -> null
          - principal_id = "0d3c3dfd-8952-4b8a-813e-c51f965ac495" -> null
          - tenant_id    = "c6874728-71e6-41fe-a9e1-2e8c36776ad8" -> null
          - type         = "SystemAssigned" -> null
        }

        # (6 unchanged blocks hidden)
    }

  # module.cloud-agent.azurerm_virtual_machine.VM["vmxwcca09"] will be updated in-place
  ~ resource "azurerm_virtual_machine" "VM" {
        id                               = "/subscriptions/876eef88-ec3d-47db-b101-ec6f9daefb65/resourceGroups/rg-xwc-app-001/providers/Microsoft.Compute/virtualMachines/vmxwcca09"
        name                             = "vmxwcca09"
        tags                             = {
            "ApplicationName"  = "VelocityLandingZone"
            "BusinessUnit"     = "MOJ"
            "CostCentre"       = "MOJ"
            "OwnerName"        = "rob.ashworth@justice.gov.uk"
            "ProjectStartDate" = "05102020"
            "RequesterName"    = "rob.ashworth@justice.gov.uk"
            "ServiceLevel"     = "Gold"
            "UpdateClass"      = "Gold1"
        }
        # (8 unchanged attributes hidden)

      - identity {
          - identity_ids = [] -> null
          - principal_id = "8696ef48-7b02-4d2b-859e-2cf073f46fa6" -> null
          - tenant_id    = "c6874728-71e6-41fe-a9e1-2e8c36776ad8" -> null
          - type         = "SystemAssigned" -> null
        }

        # (6 unchanged blocks hidden)
    }

  # module.cloud-agent.azurerm_virtual_machine.VM["vmxwcca10"] will be updated in-place
  ~ resource "azurerm_virtual_machine" "VM" {
        id                               = "/subscriptions/876eef88-ec3d-47db-b101-ec6f9daefb65/resourceGroups/rg-xwc-app-001/providers/Microsoft.Compute/virtualMachines/vmxwcca10"
        name                             = "vmxwcca10"
        tags                             = {
            "ApplicationName"  = "VelocityLandingZone"
            "BusinessUnit"     = "MOJ"
            "CostCentre"       = "MOJ"
            "OwnerName"        = "rob.ashworth@justice.gov.uk"
            "ProjectStartDate" = "05102020"
            "RequesterName"    = "rob.ashworth@justice.gov.uk"
            "ServiceLevel"     = "Gold"
            "UpdateClass"      = "Gold2"
        }
        # (8 unchanged attributes hidden)

      - identity {
          - identity_ids = [] -> null
          - principal_id = "0949b6c6-38e7-4fcd-8d56-4c2f4f246b48" -> null
          - tenant_id    = "c6874728-71e6-41fe-a9e1-2e8c36776ad8" -> null
          - type         = "SystemAssigned" -> null
        }

        # (6 unchanged blocks hidden)
    }

  # module.cloud-agent.azurerm_virtual_machine.VM["vmxwcca11"] will be updated in-place
  ~ resource "azurerm_virtual_machine" "VM" {
        id                               = "/subscriptions/876eef88-ec3d-47db-b101-ec6f9daefb65/resourceGroups/rg-xwc-app-001/providers/Microsoft.Compute/virtualMachines/vmxwcca11"
        name                             = "vmxwcca11"
        tags                             = {
            "ApplicationName"  = "VelocityLandingZone"
            "BusinessUnit"     = "MOJ"
            "CostCentre"       = "MOJ"
            "OwnerName"        = "rob.ashworth@justice.gov.uk"
            "ProjectStartDate" = "05102020"
            "RequesterName"    = "rob.ashworth@justice.gov.uk"
            "ServiceLevel"     = "Gold"
            "UpdateClass"      = "Gold1"
        }
        # (8 unchanged attributes hidden)

      - identity {
          - identity_ids = [] -> null
          - principal_id = "5f12acfa-60a4-46b2-860f-d7737abbbe34" -> null
          - tenant_id    = "c6874728-71e6-41fe-a9e1-2e8c36776ad8" -> null
          - type         = "SystemAssigned" -> null
        }

        # (6 unchanged blocks hidden)
    }

  # module.cloud-agent.azurerm_virtual_machine.VM["vmxwcca12"] will be updated in-place
  ~ resource "azurerm_virtual_machine" "VM" {
        id                               = "/subscriptions/876eef88-ec3d-47db-b101-ec6f9daefb65/resourceGroups/rg-xwc-app-001/providers/Microsoft.Compute/virtualMachines/vmxwcca12"
        name                             = "vmxwcca12"
        tags                             = {
            "ApplicationName"  = "VelocityLandingZone"
            "BusinessUnit"     = "MOJ"
            "CostCentre"       = "MOJ"
            "OwnerName"        = "rob.ashworth@justice.gov.uk"
            "ProjectStartDate" = "05102020"
            "RequesterName"    = "rob.ashworth@justice.gov.uk"
            "ServiceLevel"     = "Gold"
            "UpdateClass"      = "Gold2"
        }
        # (8 unchanged attributes hidden)

      - identity {
          - identity_ids = [] -> null
          - principal_id = "92e02930-3612-4a10-baa7-75d2dac074c7" -> null
          - tenant_id    = "c6874728-71e6-41fe-a9e1-2e8c36776ad8" -> null
          - type         = "SystemAssigned" -> null
        }

        # (6 unchanged blocks hidden)
    }

  # module.cloud-agent.azurerm_virtual_machine.VM["vmxwctestca01"] will be updated in-place
  ~ resource "azurerm_virtual_machine" "VM" {
        id                               = "/subscriptions/876eef88-ec3d-47db-b101-ec6f9daefb65/resourceGroups/rg-xwc-app-001/providers/Microsoft.Compute/virtualMachines/vmxwctestca01"
        name                             = "vmxwctestca01"
        tags                             = {
            "ApplicationName"  = "VelocityLandingZone"
            "BusinessUnit"     = "MOJ"
            "CostCentre"       = "MOJ"
            "OwnerName"        = "rob.ashworth@justice.gov.uk"
            "ProjectStartDate" = "05102020"
            "RequesterName"    = "rob.ashworth@justice.gov.uk"
            "ServiceLevel"     = "Gold"
            "UpdateClass"      = "test"
        }
        # (8 unchanged attributes hidden)

      - identity {
          - identity_ids = [] -> null
          - principal_id = "8e2af038-97cb-4f07-a995-149ea852eb7d" -> null
          - tenant_id    = "c6874728-71e6-41fe-a9e1-2e8c36776ad8" -> null
          - type         = "SystemAssigned" -> null
        }

        # (6 unchanged blocks hidden)
    }

  # module.cloud-agent.azurerm_virtual_machine.VM["vmxwctestca02"] will be updated in-place
  ~ resource "azurerm_virtual_machine" "VM" {
        id                               = "/subscriptions/876eef88-ec3d-47db-b101-ec6f9daefb65/resourceGroups/rg-xwc-app-001/providers/Microsoft.Compute/virtualMachines/vmxwctestca02"
        name                             = "vmxwctestca02"
        tags                             = {
            "ApplicationName"  = "VelocityLandingZone"
            "BusinessUnit"     = "MOJ"
            "CostCentre"       = "MOJ"
            "OwnerName"        = "rob.ashworth@justice.gov.uk"
            "ProjectStartDate" = "05102020"
            "RequesterName"    = "rob.ashworth@justice.gov.uk"
            "ServiceLevel"     = "Gold"
            "UpdateClass"      = "test"
        }
        # (8 unchanged attributes hidden)

      - identity {
          - identity_ids = [] -> null
          - principal_id = "61b9f8fd-4097-48cd-a0bf-bf8bcc37ed44" -> null
          - tenant_id    = "c6874728-71e6-41fe-a9e1-2e8c36776ad8" -> null
          - type         = "SystemAssigned" -> null
        }

        # (6 unchanged blocks hidden)
    }

  # module.device-manager.azurerm_mssql_elasticpool.elastic_pool will be updated in-place
  ~ resource "azurerm_mssql_elasticpool" "elastic_pool" {
        id                             = "/subscriptions/876eef88-ec3d-47db-b101-ec6f9daefb65/resourceGroups/rg-xwc-app-001/providers/Microsoft.Sql/servers/sqlxwcdmsrv003/elasticPools/xwc-prod-pool"
        name                           = "xwc-prod-pool"
        tags                           = {
            "ApplicationName"  = "VelocityLandingZone"
            "BusinessUnit"     = "MOJ"
            "CostCentre"       = "MOJ"
            "OwnerName"        = "rob.ashworth@justice.gov.uk"
            "ProjectStartDate" = "05102020"
            "RequesterName"    = "rob.ashworth@justice.gov.uk"
            "ServiceLevel"     = "Gold"
        }
        # (8 unchanged attributes hidden)

      ~ per_database_settings {
          ~ max_capacity = 50 -> 20
          ~ min_capacity = 20 -> 10
        }

      ~ sku {
          ~ capacity = 200 -> 100
            name     = "StandardPool"
            # (1 unchanged attribute hidden)
        }
    }

  # module.device-manager.azurerm_mssql_server.sql_server will be updated in-place
  ~ resource "azurerm_mssql_server" "sql_server" {
      ~ connection_policy                    = "Redirect" -> "Default"
        id                                   = "/subscriptions/876eef88-ec3d-47db-b101-ec6f9daefb65/resourceGroups/rg-xwc-app-001/providers/Microsoft.Sql/servers/sqlxwcdmsrv003"
        name                                 = "sqlxwcdmsrv003"
        tags                                 = {
            "ApplicationName"  = "VelocityLandingZone"
            "BusinessUnit"     = "MOJ"
            "CostCentre"       = "MOJ"
            "OwnerName"        = "rob.ashworth@justice.gov.uk"
            "ProjectStartDate" = "05102020"
            "RequesterName"    = "rob.ashworth@justice.gov.uk"
            "ServiceLevel"     = "Gold"
        }
        # (10 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 16 to change, 0 to destroy.

**Comment by staff-infrastructure-moj** [comment]
Environment: prod. Security Scan of Stage: prod has failed a IaC security scan, Please look at https://dev.azure.com/MoJ-OFFICIAL/Velocity-Landing-Zone/_build/results?buildId=53339&view=ms.vss-test-web.build-test-results-tab

**Comment by alancollier142** [comment]
Closing this PR as not able to merge as this time due to the volume of changes which have been made outside of code.

**Pull request closed without merging**
