### PR TITLE
add tags to pdnsresolver

### PR DESCRIPTION
**Pull request by alancollier142**
Add tags to pdnsresolver

### CODE REVIEW

**Comment by staff-infrastructure-moj** [comment]
Environment: dev. Pipeline Stage: dev
```
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # azurerm_private_dns_resolver.pdnsresolver will be updated in-place
  ~ resource "azurerm_private_dns_resolver" "pdnsresolver" {
        id                  = "/subscriptions/779c236c-a27b-405d-b0b8-0bbb5f7b5c67/resourceGroups/rg-xwc-dnsresolve-001/providers/Microsoft.Network/dnsResolvers/pdnsresolver"
        name                = "pdnsresolver"
      ~ tags                = {
          + "ApplicationName"  = "VelocityLandingZone"
          + "BusinessUnit"     = "MOJ"
          + "CostCentre"       = "MOJ"
          + "OwnerName"        = "rob.ashworth@justice.gov.uk"
          + "ProjectStartDate" = "05102020"
          + "RequesterName"    = "rob.ashworth@justice.gov.uk"
          + "ServiceLevel"     = "Gold"
          - "businessunit"     = "MOJ" -> null
        }
        # (3 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

**Comment by staff-infrastructure-moj** [comment]
Environment: dev. Security Scan of Stage: dev has failed a IaC security scan, Please look at https://dev.azure.com/MoJ-OFFICIAL/Velocity-Landing-Zone/_build/results?buildId=48449&view=ms.vss-test-web.build-test-results-tab

**Comment by staff-infrastructure-moj** [comment]
Environment: prod. Pipeline Stage: prod
```
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # azurerm_private_dns_resolver.pdnsresolver will be updated in-place
  ~ resource "azurerm_private_dns_resolver" "pdnsresolver" {
        id                  = "/subscriptions/876eef88-ec3d-47db-b101-ec6f9daefb65/resourceGroups/rg-xwc-dnsresolve-001/providers/Microsoft.Network/dnsResolvers/pdnsresolver"
        name                = "pdnsresolver"
      ~ tags                = {
          + "ApplicationName"  = "VelocityLandingZone"
          + "BusinessUnit"     = "MOJ"
          + "CostCentre"       = "MOJ"
          + "OwnerName"        = "rob.ashworth@justice.gov.uk"
          + "ProjectStartDate" = "05102020"
          + "RequesterName"    = "rob.ashworth@justice.gov.uk"
          + "ServiceLevel"     = "Gold"
          - "businessunit"     = "MOJ" -> null
        }
        # (3 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

**Comment by staff-infrastructure-moj** [comment]
Environment: prod. Security Scan of Stage: prod has failed a IaC security scan, Please look at https://dev.azure.com/MoJ-OFFICIAL/Velocity-Landing-Zone/_build/results?buildId=48449&view=ms.vss-test-web.build-test-results-tab

**Review by raghuvanshir — APPROVED** [review]
looks good

**Pull request merged**
